# version: '3'

services:
  rabbit:
    container_name: prambanan-service
    image: rabbitmq:3.7-management
    ports:
      - "15673:15672" # Exposing RabbitMQ web management on different port for convenience
    restart: always

  mysql:
    container_name: prambanan-mysql
    image: mysql:5.7
    ports:
      - "3307:3306" # Exposing MySQL on different port for convenience
    environment:
      MYSQL_DATABASE: "atraksi_soa"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
     - ./mysql-init:/docker-entrypoint-initdb.d
    restart: always

  aktraksi:
    build: ./atraksi
    container_name: atraksi-service
    depends_on:
      - rabbit
      - mysql
    ports:
      - "8002:8000"
    links:
      - "rabbit:prambanan-service"
      - "mysql:prambanan-mysql"
    environment:
      MYSQL_PASSWORD: "password"
      MYSQL_HOST: "mysql"
      MYSQL_DB: "atraksi_soa"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_USER: "guest"
      RABBIT_PASSWORD: "guest"
      RABBIT_MANAGEMENT_PORT: "15672"

  gateway:
    build: ./gateway
    container_name: gateway-service
    depends_on:
      - rabbit
    ports:
      - "8003:8000"
    links:
      - "rabbit:prambanan-service"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_USER: "guest"
      RABBIT_PASSWORD: "guest"
      RABBIT_MANAGEMENT_PORT: "15672"